### ISSUE TITLE
F-Droid can't build 16

### ISSUE THREAD

**Issue by licaon-kter** [ZeusLN/zeus#268]
```
ERROR: Could not build app com.zeusln.zeus: Error running prebuild command for com.zeusln.zeus:0.2.2
==== detail begin ====
+ truncate -s 0 ../../node_modules/@react-native-community/cli/build/commands/server/external/xsel
truncate: cannot open '../../node_modules/@react-native-community/cli/build/commands/server/external/xsel' for writing: No such file or directory
==== detail end ====
```

But if I edit the metadata even more:
```
    prebuild: truncate -s 0 ../../node_modules/react-native/node_modules/@react-native-community/cli/build/commands/server/external/xsel
    scanignore:
      - android/build.gradle
      - node_modules/react-native-screens/android/build.gradle
      - node_modules/react-native/template/android/build.gradle
      - node_modules/react-native-reanimated/android/build.gradle
      - node_modules/react-native-permissions/android/build.gradle
    scandelete:
      - node_modules
```
...still fails elsewhere: https://gist.github.com/licaon-kter/b23da4393943f6a7fe14f5210f4b4ed9

What are we missing?
