### ISSUE TITLE
Fails do build on F-Droid

### ISSUE THREAD

**Issue by jspricke** [ZeusLN/zeus#444]
Unable to find a matching configuration of project :react-native-tor:
https://monitor.f-droid.org/builds/log/app.zeusln.zeus/24

can you please have a look?

**Comment by linsui** [comment]
I'm working on this. react-native-tor need to be built from source. But I have some other issues...

**Comment by linsui** [comment]
I stuck on this issue:

```
> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere
error Unable to resolve module stream from /builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/cipher-base/index.js: stream could not be found within the project.
If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | var Buffer = require('safe-buffer').Buffer
> 2 | var Transform = require('stream').Transform
    |                          ^
  3 | var StringDecoder = require('string_decoder').StringDecoder
  4 | var inherits = require('inherits')
  5 | . Run CLI with --verbose flag for more details.
Error: Unable to resolve module stream from /builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/cipher-base/index.js: stream could not be found within the project.
If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | var Buffer = require('safe-buffer').Buffer
> 2 | var Transform = require('stream').Transform
    |                          ^
  3 | var StringDecoder = require('string_decoder').StringDecoder
  4 | var inherits = require('inherits')
  5 | 
    at ModuleResolver.resolveDependency (/builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:191:15)
    at DependencyGraph.resolveDependency (/builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at Object.resolve (/builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/metro/src/lib/transformHelpers.js:271:42)
    at resolve (/builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/metro/src/DeltaBundler/traverseDependencies.js:571:33)
    at dependencies.reduce (/builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/metro/src/DeltaBundler/traverseDependencies.js:587:26)
    at Array.reduce (<anonymous>)
    at resolveDependencies (/builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/metro/src/DeltaBundler/traverseDependencies.js:586:33)
    at /builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
> Task :app:bundleReleaseJsAndAssets FAILED
```

with this metadata:

```yml
  - versionName: 0.5.1
    versionCode: 24
    commit: v0.5.1
    subdir: android/app
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y g++
      - curl -Lo node.tar.xz https://nodejs.org/dist/v10.18.1/node-v10.18.1-linux-x64.tar.xz
      - echo "8cc40f45c2c62529b15e83a6bbe0ac1febf57af3c5720df68067c96c0fddbbdf node.tar.xz"
        | sha256sum -c -
      - tar xJf node.tar.xz
      - cp -a node-v10.18.1-linux-x64/. /usr/local/
    gradle:
      - yes
    output: build/outputs/apk/release/app-universal-release-unsigned.apk
    prebuild:
      - npm install
      - npm run patch-android-release
      - echo -e '\n' 'org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError
        -Dfile.encoding=UTF-8' >> ../gradle.properties
    scanignore:
      - android/build.gradle
      - node_modules
 ```
